/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GameController;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 * HappyFrog game interface.
 *
 * @author letha
 */
public class GameView extends javax.swing.JFrame {

    private GameController controller;

    /**
     * Creates new form GameView
     */
    public GameView() {
        initComponents();
        this.setTitle("Happy Frog");
        this.setLocationRelativeTo(null);
        this.controller = new GameController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnScreen = new javax.swing.JPanel();
        btPause = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        lbPoint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnScreen.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnScreen.setPreferredSize(new java.awt.Dimension(0, 350));

        javax.swing.GroupLayout pnScreenLayout = new javax.swing.GroupLayout(pnScreen);
        pnScreen.setLayout(pnScreenLayout);
        pnScreenLayout.setHorizontalGroup(
            pnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnScreenLayout.setVerticalGroup(
            pnScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        btPause.setText("Pause");
        btPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPauseActionPerformed(evt);
            }
        });

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        lbPoint.setText("Point: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btPause)
                        .addGap(18, 18, 18)
                        .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbPoint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                        .addComponent(btExit, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExit)
                    .addComponent(btPause)
                    .addComponent(btSave)
                    .addComponent(lbPoint))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handle event of pause button.
     *
     * @param evt object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPauseActionPerformed
        controller.pause();
    }//GEN-LAST:event_btPauseActionPerformed

    /**
     * Handle event of save button.
     *
     * @param evt object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        controller.save();
    }//GEN-LAST:event_btSaveActionPerformed

    /**
     * Handle event of exit button.
     *
     * @param evt object of <Code>java.awt.event.ActionEvent</Code>
     */
    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameView().setVisible(true);
            }
        });
    }

    /**
     * Get game controller.
     *
     * @return object of <Code>GameController</Code>
     */
    public GameController getController() {
        return controller;
    }

    /**
     * Set game controller.
     *
     * @param controller object of <Code>GameController</Code>
     */
    public void setController(GameController controller) {
        this.controller = controller;
    }

    /**
     * Get exit button.
     *
     * @return object of <Code>JButton</Code>
     */
    public JButton getBtExit() {
        return btExit;
    }

    /**
     * Set exit button.
     *
     * @param btExit object of <Code>JButton</Code>
     */
    public void setBtExit(JButton btExit) {
        this.btExit = btExit;
    }

    /**
     * Get pause button.
     *
     * @return object of <Code>JButton</Code>
     */
    public JButton getBtPause() {
        return btPause;
    }

    /**
     * Set pause button.
     *
     * @param btPause object of <Code>JButton</Code>
     */
    public void setBtPause(JButton btPause) {
        this.btPause = btPause;
    }

    /**
     * Get save button.
     *
     * @return object of <Code>JButton</Code>
     */
    public JButton getBtSave() {
        return btSave;
    }

    /**
     * Set save button.
     *
     * @param btSave object of <Code>JButton</Code>
     */
    public void setBtSave(JButton btSave) {
        this.btSave = btSave;
    }

    /**
     * Get label of point.
     *
     * @return object of <Code>JLabel</Code>
     */
    public JLabel getLbPoint() {
        return lbPoint;
    }

    /**
     * Set label of point.
     *
     * @param lbPoint object of <Code>JLabel</Code>
     */
    public void setLbPoint(JLabel lbPoint) {
        this.lbPoint = lbPoint;
    }

    /**
     * Get game panel.
     *
     * @return object of <Code>JPanel</Code>
     */
    public JPanel getPnScreen() {
        return pnScreen;
    }

    /**
     * Set game panel.
     *
     * @param pnScreen object of <Code>JPanel</Code>
     */
    public void setPnScreen(JPanel pnScreen) {
        this.pnScreen = pnScreen;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExit;
    private javax.swing.JButton btPause;
    private javax.swing.JButton btSave;
    private javax.swing.JLabel lbPoint;
    private javax.swing.JPanel pnScreen;
    // End of variables declaration//GEN-END:variables
}
